akhq:
  connections:
    localhost-sasl:
      properties:
        bootstrap.servers: "localhost:9092"
        security.protocol: PLAINTEXT
        ssl.endpoint.identification.algorithm: ""
      schema-registry:
        enabled: true
        url: http://localhost:8081
#        basic-auth-username: user
#        basic-auth-password: password
micronaut:
  server:
    port: 8089
