spring:
  application:
    name: springboot-kafka-avro
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
#      value-serializer: com.example.demo.demokafka.config.KafkaEventSerializer
    listener:
      missing-topics-fatal: false
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  kafka:
    retry:
      topic:
        main:
          timems: ${KAFKA_RETRY_TIMEMS_MAIN_TOPIC:0}
          max: ${KAFKA_RETRY_MAX_MAIN_TOPIC:0}
        retry:
          timems: ${KAFKA_RETRY_TIMEMS:30000}
          max: ${KAFKA_RETRY_MAX:3}
    my-consumer:
      enabled: ${CONSUMER_ENABLED}
      topic:
        main: ${TOPIC_MAIN}
        retry: ${TOPIC_RETRY}
        error: ${TOPIC_DLT}
        output: ${TOPIC_OUTPUT}
      auto-offset-reset: latest
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
      client-id: ${KAFKA_CLIENT_ID}
      group-id: ${KAFKA_GROUP_ID}
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      max-poll-records: 5
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        deserializer-key-delegate-class: org.apache.kafka.common.serialization.StringDeserializer
        deserializer-value-delegate-class: io.confluent.kafka.serializers.KafkaAvroDeserializer
#        deserializer-value-delegate-class: com.example.demo.demokafka.config.KafkaEventDeserializer
        json-trusted-packages: '"*"'
        value-deserializer-specific-avro-reader: true
      schema-registry:
        url: ${SCHEMA_REGISTRY_URL}
  external-api:
    url: ${EXTERNAL_URL}


logging:
  level:
    root: info